trajectory_planner:
  ros__parameters:
    odom_topic: "/initialpose"
    offline: False
trajectory_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/low_level/input/navigation"
